package com.example.json_ghh

import org.json.JSONObject

data class Eur (
    val ada: Double,
    val aed: Double,
    val afn: Double,
    val all: Double,
    val amd: Double,
    val ang: Double,
    val aoa: Double,
    val ars: Double,
    val aud: Double,
    val awg: Double,
    val azn: Double,
    val bam: Double,
    val bbd: Double,
    val bch: Double,
    val bdt: Double,
    val bgn: Double,
    val bhd: Double,
    val bif: Double,
    val bmd: Double,
    val bnb: Double,
    val sar : Double,
    val usd : Double,
    val bnd: Double,
    val bob: Double,
    val brl: Double,
    val bsd: Double,
    val btc: Double,
    val btn: Double,
    val bwp: Double,
    val byn: Double,
    val byr: Double,
    val bzd: Double,
    val cad: Double,
    val cdf: Double,
    val chf: Double,
    val clf: Double,
    val clp: Double,
    val cny: Double,
    val cop: Double,
    val crc: Double,
    val cuc: Double,
    val cup: Double

    ,
    val cve: Double,
    val czk: Double,
    val djf: Double,
    val dkk: Double,
    val doge: Double,
    val dop: Double,
    val dzd: Double,
    val egp: Double,
    val ern: Double,
    val etb: Double,
    val etc: Double,
    val eth: Double,
    val eur: Int,
    val fjd: Double,
    val fkp: Double,
    val gbp: Double,
    val gel: Double,
    val ggp: Double,
    val ghs: Double,
    val gip: Double

    ,
    val gmd: Double,
    val gnf: Double,
    val gtq: Double,
    val gyd: Double,
    val hkd: Double,
    val hnl: Double,
    val hrk: Double,
    val htg: Double,
    val huf: Double,
    val idr: Double,
    val ils: Double,
    val imp: Double,
    val inr: Double,
    val iqd: Double,
    val irr: Double,
    val isk: Double,
    val jep: Double,
    val jmd: Double,
    val jod: Double,
    val jpy: Double

)